---
# tasks file for ansible-role-openmdns

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Start openmdns
  service:
    name: "{{ openmdns_service }}"
    state: started
